---
title: "NRES803"
author: "Nieto_Lopez"
date: "5/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```
## Setting the packages and wrangling

```{r set packages, echo=FALSE}
#Hi alll l

packages <- c("tidyverse","agricolae", "mosaic", "broom", "car","lawstat", "ggridges", "cowplot", "gridExtra", "arsenal", "DescTools","ezec")
lapply( packages, require, character.only = TRUE)

#####boscalid

boscalid.data <-
  read.csv("data/boscalid.csv")
  
  boscalid.data$repeats <- rep_len(1:4, length.out = nrow(boscalid.data))
  boscalid.data$ID <- as.character(boscalid.data$ID)
  # renaming ID for the current names
 boscalid.data$ID[ boscalid.data$ID =="541B"]  <- "541" 

 boscalid.data$ID[ boscalid.data$ID =="293E"]  <- "293" 
 boscalid.data$ID[ boscalid.data$ID =="973B"]  <- "973" 
 boscalid.data$ID[ boscalid.data$ID =="973C"]  <- "973" 
  boscalid.data$ID[ boscalid.data$ID =="973D"]  <- "973" 
 boscalid.data$ID[ boscalid.data$ID =="974A"]  <- "974" 
 boscalid.data$ID[ boscalid.data$ID =="974B"]  <- "974" 
 boscalid.data$ID[ boscalid.data$ID =="974C"]  <- "974" 
 boscalid.data$ID[ boscalid.data$ID =="974D"]  <- "974" 
 boscalid.data$ID[ boscalid.data$ID =="975C"]  <- "975" 
 boscalid.data$ID[ boscalid.data$ID =="975D"]  <- "975" 
 boscalid.data$ID[ boscalid.data$ID =="975E"]  <- "975" 
 boscalid.data$ID[ boscalid.data$ID =="976B"]  <- "976"
 boscalid.data$ID[ boscalid.data$ID =="976C"]  <- "976"
 boscalid.data$ID[ boscalid.data$ID =="977B"]  <- "977"
 boscalid.data$ID[ boscalid.data$ID =="978B"]  <- "978"

 str_squish(boscalid.data$ID)
  ####Transforming to $ID to numeric
 boscalid.data$ID <- as.numeric(boscalid.data$ID)
  # Filter out 
  boscalid.data <- boscalid.data %>%
     #filter(!dose ==  0.4 & !ID == 800) %>%
    mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
    

  boscalid.SG <-
  read.csv("data/1_Day_SG/Boscalid.csv")
  
  boscalid.SG <- boscalid.SG %>% 
    rename(ID= Isolate)
  
  boscalid.SG$ID <- as.character(boscalid.SG$ID)
  # renaming ID for the current names
 boscalid.SG$ID[ boscalid.SG$ID =="541B"]  <- "541" 

 boscalid.SG$ID[ boscalid.SG$ID =="293E"]  <- "293" 
 boscalid.SG$ID[ boscalid.SG$ID =="973B"]  <- "973" 
 boscalid.SG$ID[ boscalid.SG$ID =="973C"]  <- "973" 
  boscalid.SG$ID[ boscalid.SG$ID =="973D"]  <- "973" 
 boscalid.SG$ID[ boscalid.SG$ID =="974A"]  <- "974" 
 boscalid.SG$ID[ boscalid.SG$ID =="974B"]  <- "974" 
 boscalid.SG$ID[ boscalid.SG$ID =="974C"]  <- "974" 
 boscalid.SG$ID[ boscalid.SG$ID =="974D"]  <- "974" 
 boscalid.SG$ID[ boscalid.SG$ID =="975C"]  <- "975" 
 boscalid.SG$ID[ boscalid.SG$ID =="975D"]  <- "975" 
 boscalid.SG$ID[ boscalid.SG$ID =="975E"]  <- "975" 
 boscalid.SG$ID[ boscalid.SG$ID =="976B"]  <- "976"
 boscalid.SG$ID[ boscalid.SG$ID =="976C"]  <- "976"
 boscalid.SG$ID[ boscalid.SG$ID =="977B"]  <- "977"
 boscalid.SG$ID[ boscalid.SG$ID =="978B"]  <- "978"

 str_squish(boscalid.SG$ID)
  ####Transforming to $ID to numeric
 boscalid.SG$ID <- as.numeric(boscalid.SG$ID)
  # Filter out 
  boscalid.SG <- boscalid.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()
  
  ###Fluazinam
  
fluazinam.data <-
  read.csv("data/fluazinam.csv")
  
  fluazinam.data$repeats <- rep_len(1:4, length.out = nrow(fluazinam.data))
  fluazinam.data$ID <- as.character(fluazinam.data$ID)
  # renaming ID for the current names
 fluazinam.data$ID[ fluazinam.data$ID =="541B"]  <- "541" 

 fluazinam.data$ID[ fluazinam.data$ID =="293E"]  <- "293" 
 fluazinam.data$ID[ fluazinam.data$ID =="973B"]  <- "973" 
 fluazinam.data$ID[ fluazinam.data$ID =="973C"]  <- "973" 
  fluazinam.data$ID[ fluazinam.data$ID =="973D"]  <- "973"
 fluazinam.data$ID[ fluazinam.data$ID =="974A"]  <- "974" 
 fluazinam.data$ID[ fluazinam.data$ID =="974B"]  <- "974" 
 fluazinam.data$ID[ fluazinam.data$ID =="974C"]  <- "974" 
 fluazinam.data$ID[ fluazinam.data$ID =="974D"]  <- "974" 
 fluazinam.data$ID[ fluazinam.data$ID =="975C"]  <- "975" 
 fluazinam.data$ID[ fluazinam.data$ID =="975D"]  <- "975" 
 fluazinam.data$ID[ fluazinam.data$ID =="975E"]  <- "975" 
 fluazinam.data$ID[ fluazinam.data$ID =="976B"]  <- "976"
 fluazinam.data$ID[ fluazinam.data$ID =="976C"]  <- "976"
 fluazinam.data$ID[ fluazinam.data$ID =="977B"]  <- "977"
 fluazinam.data$ID[ fluazinam.data$ID =="978B"]  <- "978"

 str_squish(fluazinam.data$ID)
  ####Transforming to $ID to numeric
 fluazinam.data$ID <- as.numeric(fluazinam.data$ID)
  # Filter out 
  fluazinam.data <- fluazinam.data %>%
     #filter(!dose ==  0.4 & !ID == 800) %>%
    mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
 
  #
  
  fluazinam.SG <-
  read.csv("data/1_Day_SG/Fluazinam.csv")
  
  fluazinam.SG <- fluazinam.SG %>% 
    rename(ID= Isolate)
  
  fluazinam.SG$ID <- as.character(fluazinam.SG$ID)
  # renaming ID for the current names
 fluazinam.SG$ID[ fluazinam.SG$ID =="541B"]  <- "541" 

 fluazinam.SG$ID[ fluazinam.SG$ID =="293E"]  <- "293" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="973B"]  <- "973" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="973C"]  <- "973" 
  fluazinam.SG$ID[ fluazinam.SG$ID =="973D"]  <- "973" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="974A"]  <- "974" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="974B"]  <- "974" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="974C"]  <- "974" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="974D"]  <- "974" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="975C"]  <- "975" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="975D"]  <- "975" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="975E"]  <- "975" 
 fluazinam.SG$ID[ fluazinam.SG$ID =="976B"]  <- "976"
 fluazinam.SG$ID[ fluazinam.SG$ID =="976C"]  <- "976"
 fluazinam.SG$ID[ fluazinam.SG$ID =="977B"]  <- "977"
 fluazinam.SG$ID[ fluazinam.SG$ID =="978B"]  <- "978"

 str_squish(fluazinam.SG$ID)
  ####Transforming to $ID to numeric
 fluazinam.SG$ID <- as.numeric(fluazinam.SG$ID)
  # Filter out 
  fluazinam.SG <- fluazinam.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()


  
   #######Iprodione
  
  iprodione.data <-
  read.csv("data/iprodione.csv")
  
  iprodione.data$repeats <- rep_len(1:4, length.out = nrow(iprodione.data))
  iprodione.data$ID <- as.character(iprodione.data$ID)
  # renaming ID for the current names
 iprodione.data$ID[ iprodione.data$ID =="541B"]  <- "541" 

 iprodione.data$ID[ iprodione.data$ID =="293E"]  <- "293" 
 iprodione.data$ID[ iprodione.data$ID =="973B"]  <- "973" 
 iprodione.data$ID[ iprodione.data$ID =="973C"]  <- "973" 
 iprodione.data$ID[ iprodione.data$ID =="973D"]  <- "973"
 iprodione.data$ID[ iprodione.data$ID =="974A"]  <- "974" 
 iprodione.data$ID[ iprodione.data$ID =="974B"]  <- "974" 
 iprodione.data$ID[ iprodione.data$ID =="974C"]  <- "974" 
 iprodione.data$ID[ iprodione.data$ID =="974D"]  <- "974" 
 iprodione.data$ID[ iprodione.data$ID =="975C"]  <- "975" 
 iprodione.data$ID[ iprodione.data$ID =="975D"]  <- "975" 
 iprodione.data$ID[ iprodione.data$ID =="975E"]  <- "975" 
 iprodione.data$ID[ iprodione.data$ID =="976B"]  <- "976"
 iprodione.data$ID[ iprodione.data$ID =="976C"]  <- "976"
 iprodione.data$ID[ iprodione.data$ID =="977B"]  <- "977"
 iprodione.data$ID[ iprodione.data$ID =="978B"]  <- "978"

 str_squish(iprodione.data$ID)
  ####Transforming to $ID to numeric
 iprodione.data$ID <- as.numeric(iprodione.data$ID)
  # Filter out 
  iprodione.data <- iprodione.data %>%
         mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
    
iprodione.SG <-
  read.csv("data/1_Day_SG/Iprodione.csv")
  
  iprodione.SG <- iprodione.SG %>% 
    rename(ID= Isolate)
  
  iprodione.SG$ID <- as.character(iprodione.SG$ID)
  # renaming ID for the current names
 iprodione.SG$ID[ iprodione.SG$ID =="541B"]  <- "541" 

 iprodione.SG$ID[ iprodione.SG$ID =="293E"]  <- "293" 
 iprodione.SG$ID[ iprodione.SG$ID =="973B"]  <- "973" 
 iprodione.SG$ID[ iprodione.SG$ID =="973C"]  <- "973" 
  iprodione.SG$ID[ iprodione.SG$ID =="973D"]  <- "973" 
 iprodione.SG$ID[ iprodione.SG$ID =="974A"]  <- "974" 
 iprodione.SG$ID[ iprodione.SG$ID =="974B"]  <- "974" 
 iprodione.SG$ID[ iprodione.SG$ID =="974C"]  <- "974" 
 iprodione.SG$ID[ iprodione.SG$ID =="974D"]  <- "974" 
 iprodione.SG$ID[ iprodione.SG$ID =="975C"]  <- "975" 
 iprodione.SG$ID[ iprodione.SG$ID =="975D"]  <- "975" 
 iprodione.SG$ID[ iprodione.SG$ID =="975E"]  <- "975" 
 iprodione.SG$ID[ iprodione.SG$ID =="976B"]  <- "976"
 iprodione.SG$ID[ iprodione.SG$ID =="976C"]  <- "976"
 iprodione.SG$ID[ iprodione.SG$ID =="977B"]  <- "977"
 iprodione.SG$ID[ iprodione.SG$ID =="978B"]  <- "978"

 str_squish(iprodione.SG$ID)
  ####Transforming to $ID to numeric
 iprodione.SG$ID <- as.numeric(iprodione.SG$ID)
  # Filter out 
  iprodione.SG <- iprodione.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()
  
    
  
###Procymidone
  
procymidone.data <-
  read.csv("data/procymidone.csv")
  
  procymidone.data$repeats <- rep_len(1:4, length.out = nrow(procymidone.data))
  procymidone.data$ID <- as.character(procymidone.data$ID)
  # renaming ID for the current names
 procymidone.data$ID[ procymidone.data$ID =="541B"]  <- "541" 

 procymidone.data$ID[ procymidone.data$ID =="293E"]  <- "293" 
 procymidone.data$ID[ procymidone.data$ID =="973B"]  <- "973" 
 procymidone.data$ID[ procymidone.data$ID =="973C"]  <- "973" 
  procymidone.data$ID[ procymidone.data$ID =="973D"]  <- "973" 
 procymidone.data$ID[ procymidone.data$ID =="974A"]  <- "974" 
 procymidone.data$ID[ procymidone.data$ID =="974B"]  <- "974" 
 procymidone.data$ID[ procymidone.data$ID =="974C"]  <- "974" 
 procymidone.data$ID[ procymidone.data$ID =="974D"]  <- "974" 
 procymidone.data$ID[ procymidone.data$ID =="975C"]  <- "975" 
 procymidone.data$ID[ procymidone.data$ID =="975D"]  <- "975" 
 procymidone.data$ID[ procymidone.data$ID =="975E"]  <- "975" 
 procymidone.data$ID[ procymidone.data$ID =="976B"]  <- "976"
 procymidone.data$ID[ procymidone.data$ID =="976C"]  <- "976"
 procymidone.data$ID[ procymidone.data$ID =="977B"]  <- "977"
 procymidone.data$ID[ procymidone.data$ID =="978B"]  <- "978"

 str_squish(procymidone.data$ID)
  ####Transforming to $ID to numeric
 procymidone.data$ID <- as.numeric(procymidone.data$ID)
  # Filter out 
  procymidone.data <- procymidone.data %>%
     #filter(!dose ==  0.4 & !ID == 800) %>%
    mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
  
  procymidone.SG <-
  read.csv("data/1_Day_SG/Procymidone.csv")
  
  procymidone.SG <- procymidone.SG %>% 
    rename(ID= Isolate)
  
  procymidone.SG$ID <- as.character(procymidone.SG$ID)
  # renaming ID for the current names
 procymidone.SG$ID[ procymidone.SG$ID =="541B"]  <- "541" 

 procymidone.SG$ID[ procymidone.SG$ID =="293E"]  <- "293" 
 procymidone.SG$ID[ procymidone.SG$ID =="973B"]  <- "973" 
 procymidone.SG$ID[ procymidone.SG$ID =="973C"]  <- "973" 
  procymidone.SG$ID[ procymidone.SG$ID =="973D"]  <- "973" 
 procymidone.SG$ID[ procymidone.SG$ID =="974A"]  <- "974" 
 procymidone.SG$ID[ procymidone.SG$ID =="974B"]  <- "974" 
 procymidone.SG$ID[ procymidone.SG$ID =="974C"]  <- "974" 
 procymidone.SG$ID[ procymidone.SG$ID =="974D"]  <- "974" 
 procymidone.SG$ID[ procymidone.SG$ID =="975C"]  <- "975" 
 procymidone.SG$ID[ procymidone.SG$ID =="975D"]  <- "975" 
 procymidone.SG$ID[ procymidone.SG$ID =="975E"]  <- "975" 
 procymidone.SG$ID[ procymidone.SG$ID =="976B"]  <- "976"
 procymidone.SG$ID[ procymidone.SG$ID =="976C"]  <- "976"
 procymidone.SG$ID[ procymidone.SG$ID =="977B"]  <- "977"
 procymidone.SG$ID[ procymidone.SG$ID =="978B"]  <- "978"

 str_squish(procymidone.SG$ID)
  ####Transforming to $ID to numeric
 procymidone.SG$ID <- as.numeric(procymidone.SG$ID)
  # Filter out 
  procymidone.SG <- procymidone.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()
    
  
  ###Prothioconazole
  prothioconazole.data <-
  read.csv("data/prothioconazole.csv")
  
  prothioconazole.data$repeats <- rep_len(1:4, length.out = nrow(prothioconazole.data))
  prothioconazole.data$ID <- as.character(prothioconazole.data$ID)
  # renaming ID for the current names
 prothioconazole.data$ID[ prothioconazole.data$ID =="541B"]  <- "541" 

 prothioconazole.data$ID[ prothioconazole.data$ID =="293E"]  <- "293" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="973B"]  <- "973" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="973C"]  <- "973"
 prothioconazole.data$ID[ prothioconazole.data$ID =="973D"]  <- "973"
 prothioconazole.data$ID[ prothioconazole.data$ID =="974A"]  <- "974" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="974B"]  <- "974" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="974C"]  <- "974" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="974D"]  <- "974" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="975C"]  <- "975" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="975D"]  <- "975" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="975E"]  <- "975" 
 prothioconazole.data$ID[ prothioconazole.data$ID =="976B"]  <- "976"
 prothioconazole.data$ID[ prothioconazole.data$ID =="976C"]  <- "976"
 prothioconazole.data$ID[ prothioconazole.data$ID =="977B"]  <- "977"
 prothioconazole.data$ID[ prothioconazole.data$ID =="978B"]  <- "978"

 str_squish(prothioconazole.data$ID)
  ####Transforming to $ID to numeric
 prothioconazole.data$ID <- as.numeric(prothioconazole.data$ID)
  # Filter out 
  prothioconazole.data <- prothioconazole.data %>%
     #filter(!dose ==  0.4 & !ID == 800) %>%
    mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
    
  prothioconazole.SG <-
  read.csv("data/1_Day_SG/Prothioconazole.csv")
  
  prothioconazole.SG <- prothioconazole.SG %>% 
    rename(ID= Isolate)
  
  prothioconazole.SG$ID <- as.character(prothioconazole.SG$ID)
  # renaming ID for the current names
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="541B"]  <- "541" 

 prothioconazole.SG$ID[ prothioconazole.SG$ID =="293E"]  <- "293" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="973B"]  <- "973" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="973C"]  <- "973" 
  prothioconazole.SG$ID[ prothioconazole.SG$ID =="973D"]  <- "973" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="974A"]  <- "974" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="974B"]  <- "974" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="974C"]  <- "974" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="974D"]  <- "974" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="975C"]  <- "975" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="975D"]  <- "975" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="975E"]  <- "975" 
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="976B"]  <- "976"
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="976C"]  <- "976"
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="977B"]  <- "977"
 prothioconazole.SG$ID[ prothioconazole.SG$ID =="978B"]  <- "978"

 str_squish(prothioconazole.SG$ID)
  ####Transforming to $ID to numeric
 prothioconazole.SG$ID <- as.numeric(prothioconazole.SG$ID)
  # Filter out 
  prothioconazole.SG <- prothioconazole.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()
  
  
##pyraclostrobin
  pyraclostrobin.data <-
  read.csv("data/pyraclostrobin.csv")
  
  pyraclostrobin.data$repeats <- rep_len(1:4, length.out = nrow(pyraclostrobin.data))
  pyraclostrobin.data$ID <- as.character(pyraclostrobin.data$ID)
  # renaming ID for the current names
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="541B"]  <- "541" 

 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="293E"]  <- "293" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="973B"]  <- "973" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="973C"]  <- "973"
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="973D"]  <- "973"
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="974A"]  <- "974" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="974B"]  <- "974" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="974C"]  <- "974" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="974D"]  <- "974" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="975C"]  <- "975" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="975D"]  <- "975" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="975E"]  <- "975" 
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="976B"]  <- "976"
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="976C"]  <- "976"
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="977B"]  <- "977"
 pyraclostrobin.data$ID[ pyraclostrobin.data$ID =="978B"]  <- "978"

 str_squish(pyraclostrobin.data$ID)
  ####Transforming to $ID to numeric
 pyraclostrobin.data$ID <- as.numeric(pyraclostrobin.data$ID)
  # Filter out 
  pyraclostrobin.data <- pyraclostrobin.data %>%
     #filter(!dose ==  0.4 & !ID == 800) %>%
    mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
  
  pyraclostrobin.SG <-
  read.csv("data/1_Day_SG/Pyraclostrobin.csv")
  
  pyraclostrobin.SG <- pyraclostrobin.SG %>% 
    rename(ID= Isolate)
  
  pyraclostrobin.SG$ID <- as.character(pyraclostrobin.SG$ID)
  # renaming ID for the current names
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="541B"]  <- "541" 

 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="293E"]  <- "293" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="973B"]  <- "973" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="973C"]  <- "973" 
  pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="973D"]  <- "973" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="974A"]  <- "974" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="974B"]  <- "974" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="974C"]  <- "974" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="974D"]  <- "974" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="975C"]  <- "975" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="975D"]  <- "975" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="975E"]  <- "975" 
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="976B"]  <- "976"
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="976C"]  <- "976"
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="977B"]  <- "977"
 pyraclostrobin.SG$ID[ pyraclostrobin.SG$ID =="978B"]  <- "978"

 str_squish(pyraclostrobin.SG$ID)
  ####Transforming to $ID to numeric
 pyraclostrobin.SG$ID <- as.numeric(pyraclostrobin.SG$ID)
  # Filter out 
  pyraclostrobin.SG <- pyraclostrobin.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()
  
  
  #thiophanate_methyl
  
  thiophanate_methyl.data <-
  read.csv("data/thiophanate_methyl.csv")
  
  thiophanate_methyl.data$repeats <- rep_len(1:4, length.out = nrow(thiophanate_methyl.data))
  thiophanate_methyl.data$ID <- as.character(thiophanate_methyl.data$ID)
  # renaming ID for the current names
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="541B"]  <- "541" 

 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="293E"]  <- "293" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="973B"]  <- "973" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="973C"]  <- "973" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="973D"]  <- "973" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="974A"]  <- "974" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="974B"]  <- "974" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="974C"]  <- "974" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="974D"]  <- "974" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="975C"]  <- "975" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="975D"]  <- "975" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="975E"]  <- "975" 
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="976B"]  <- "976"
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="976C"]  <- "976"
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="977B"]  <- "977"
 thiophanate_methyl.data$ID[ thiophanate_methyl.data$ID =="978B"]  <- "978"

 str_squish(thiophanate_methyl.data$ID)
  ####Transforming to $ID to numeric
 thiophanate_methyl.data$ID <- as.numeric(thiophanate_methyl.data$ID)
  # Filter out 
  #thiophanate_methyl.data <- thiophanate_methyl.data %>%
     
   # mutate(response= replace(response, response == 0, 0.6))  #replacing 0 cm growth for the size of plug that is 0.6
    
 thiophanate_methyl.SG <-
  read.csv("data/1_Day_SG/Thiophanate_methyl.csv",  na.strings = TRUE)
  
  thiophanate_methyl.SG <- thiophanate_methyl.SG %>% 
    rename(ID= Isolate)
  
  thiophanate_methyl.SG$ID <- as.character(thiophanate_methyl.SG$ID)
  # renaming ID for the current names
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="541B"]  <- "541" 

 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="293E"]  <- "293" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="973B"]  <- "973" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="973C"]  <- "973" 
  thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="973D"]  <- "973" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="974A"]  <- "974" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="974B"]  <- "974" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="974C"]  <- "974" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="974D"]  <- "974" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="975C"]  <- "975" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="975D"]  <- "975" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="975E"]  <- "975" 
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="976B"]  <- "976"
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="976C"]  <- "976"
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="977B"]  <- "977"
 thiophanate_methyl.SG$ID[ thiophanate_methyl.SG$ID =="978B"]  <- "978"

 str_squish(thiophanate_methyl.SG$ID)
  ####Transforming to $ID to numeric
 thiophanate_methyl.SG$ID <- as.numeric(thiophanate_methyl.SG$ID)
  # Filter out 
  thiophanate_methyl.SG <- thiophanate_methyl.SG %>%
    group_by(ID) %>%  
    mutate(Average=mean(EC50)) %>% 
    select(- EC50) %>% 
    rename(EC50_SG= Average) %>% 
    unique() %>% 
    ungroup()
 
  
  

  
  #Function

 get_range <- function(mynumber) {
  bb <- boxplot.stats(mynumber)
  cc <- bb$stats
  dd <- max(cc)
  ee <- min(cc)
  return(data.frame(upper = dd, lower = ee))
}
  
 
 boscalid.filtered <- boscalid.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 aa <- EC_table(boscalid.filtered, form = response ~ dose)

boscalid.PD <-
  aa %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 boscalid.final <- boscalid.PD %>% 
    left_join(boscalid.SG)

 ##
 fluazinam.filtered <- fluazinam.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 bb <- EC_table(fluazinam.filtered, form = response ~ dose)

fluazinam.PD <-
  bb %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 fluazinam.final <- fluazinam.PD %>% 
    left_join(fluazinam.SG)
#
 iprodione.filtered <- iprodione.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 cc <- EC_table(iprodione.filtered, form = response ~ dose)

iprodione.PD <-
  cc %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 iprodione.final <- iprodione.PD %>% 
    left_join(iprodione.SG)
##
 procymidone.filtered <- procymidone.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 dd <- EC_table(procymidone.filtered, form = response ~ dose)

procymidone.PD <-
  dd %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 procymidone.final <- procymidone.PD %>% 
    left_join(procymidone.SG)
#
 prothioconazole.filtered <- prothioconazole.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 ee <- EC_table(prothioconazole.filtered, form = response ~ dose)

prothioconazole.PD <-
  ee %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 prothioconazole.final <- prothioconazole.PD %>% 
    left_join(prothioconazole.SG)
#
 pyraclostrobin.filtered <- pyraclostrobin.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 ff <- EC_table(pyraclostrobin.filtered, form = response ~ dose)

pyraclostrobin.PD <-
  ff %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 pyraclostrobin.final <- pyraclostrobin.PD %>% 
    left_join(pyraclostrobin.SG)
#
 thiophanate_methyl.filtered <- thiophanate_methyl.data %>%
  group_by(ID, dose) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower) %>%
  ungroup() %>%
  select(c(ID, dose, response, repeats))
   
 gg <- EC_table(thiophanate_methyl.filtered, form = response ~ dose)

thiophanate_methyl.PD <-
  gg %>% rename(ID = sample ) %>% # renaming
  rename(EC50_PD = Estimate.50) %>% 
  select(ID, EC50_PD)
 
 thiophanate_methyl.final <- thiophanate_methyl.PD %>% 
    left_join(thiophanate_methyl.SG)

####
plug.discs <- read.csv("data/Paper_discs_vs_PLUG.csv", stringsAsFactors = TRUE, na.strings = TRUE)
plug.discs$Fungicide <- str_squish(plug.discs$Fungicide)
stopifnot(nrow(plug.discs) == 7*11*2*2*2*4)
#Y <- read.csv("data/Paper_discs_vs_PLUG.csv", stringsAsFactors = TRUE, na.strings = TRUE)

#stopifnot(nrow(plugdiscs)== 7*11*2*2*2*4)
plug.discs <- plug.discs %>% 
mutate(inoculum= as.character(inoculum)) %>% 
rename(ID= inoculum, 
      experimental_replicate = experimental_repetition) %>%
  select(Fungicide, ID, experiment, experimental_replicate, treatment, growth) %>% 
     group_by(Fungicide, ID,experiment, experimental_replicate, treatment) %>% mutate(rep= 1:4) %>% spread( treatment, growth ) %>% 
  ungroup()
 # group_by(ID, experiment, experimental_repeatlicate)
   #spread( treatment )
```

```{r}
#Function
get_range <- function(mynumber) {
  bb <- boxplot.stats(mynumber)
  cc <- bb$stats
  dd <- max(cc)
  ee <- min(cc)
  return(data.frame(upper = dd, lower = ee))
}

```
##  By fungicide
## prothioconazole
```{r prothioconazole}

#prothioconazole
prothioconazole.plug.discs <-  plug.discs %>% filter(Fungicide== "prothioconazole") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
prothioconazole.plug.discs.filtered <-  prothioconazole.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
prothioconazole.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 

# transforming to log 
prothioconazole.plug.discs.filtered.2 <-  prothioconazole.plug.discs.filtered %>% 
  mutate(log.inhibition= log(inhibition))
###
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
prothioconazole.plug.discs.filtered.2 %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$log.inhibition)))


prothioconazole.1 <- lm()

#non parametric between experimental repeatlicates and experiment, there is differenc between experiment and experimental replicates, so I cant join data from experimental replicates
prothioconazole.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experimental_replicate, 
    data = .) 


prothioconazole.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experiment, 
    data = .) 

# Now Dunn test

 prothioconazole.plug.discs.filtered  %>% DunnTest(inhibition ~ experiment,data = ., method = "bonferroni")
#P VALUE 0.000016 *** plug-paper


```
## Fluazinam
```{r Fluazinam}
#Fluazinam
fluazinam.plug.discs <-  plug.discs %>% filter(Fungicide== "fluazinam") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
fluazinam.plug.discs.filtered <-  fluazinam.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There is normality between experimental replicates
fluazinam.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 

#ANOVA between experimental repeatlicates and experiment, there is difference between experiment and experimental replicates, so I cant join data from experimental replicates

fluazinam.plug.discs.filtered  %>% 
  aov(inhibition ~ experiment  + experimental_replicate, 
    data = .) %>% 
  summary()

```
## Iprodione
```{r Iprodione}

iprodione.plug.discs <-  plug.discs %>% filter(Fungicide== "iprodione") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
iprodione.plug.discs.filtered <-  iprodione.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There is normality in one exp replicate but not in the other one
iprodione.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 


# transforming to log 
iprodione.plug.discs.filtered.2 <-  iprodione.plug.discs.filtered %>% 
  mutate(log.inhibition= log(inhibition))
###
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
iprodione.plug.discs.filtered.2 %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$log.inhibition)))


#non parametric test between experimental repeatlicates and experiment, there is differenc between experiment and experimental replicates, so I cant join data from experimental replicates

iprodione.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experimental_replicate, 
    data = .) 


iprodione.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experiment, 
    data = .) 

# Now Dunn test

 iprodione.plug.discs.filtered  %>% DunnTest(inhibition ~ experiment,data = ., method = "bonferroni")
#P VALUE 0.0258 *plug-paper


```
## Procymidone
```{r Procymidone}

procymidone.plug.discs <-  plug.discs %>% filter(Fungicide== "procymidone") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
procymidone.plug.discs.filtered <-  procymidone.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There is normality in one experimental replicate but not in the other one
procymidone.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 

# transforming to square
procymidone.plug.discs.filtered.2 <-  procymidone.plug.discs.filtered %>% 
  mutate(square.inhibition= inhibition^2)
###
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
procymidone.plug.discs.filtered.2 %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$square.inhibition)))


# non parametric test between experimental repeatlicates and experiment, there is differenc between  experimental replicates (so I cant join data from experimental) but not  between experiments

procymidone.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experimental_replicate, 
    data = .) 


procymidone.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experiment, 
    data = .)  
#p value = 0.09274


```

## Prothioconazole
```{r Prothioconazole}
## Prothioconazole
prothioconazole.plug.discs <-  plug.discs %>% filter(Fungicide== "prothioconazole") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
prothioconazole.plug.discs.filtered <-  prothioconazole.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
prothioconazole.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 

# transforming to log 
prothioconazole.plug.discs.filtered.2 <-  prothioconazole.plug.discs.filtered %>% 
  mutate(log.inhibition= log(inhibition))
###
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
prothioconazole.plug.discs.filtered.2 %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$log.inhibition)))


# non parametric test between experimental repeatlicates and experiment, there is no difference between experiment and  experimental replicates, so I can join data from experimental replicates

prothioconazole.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experimental_replicate, 
    data = .) 


prothioconazole.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experiment, 
    data = .) 


```
## Pyraclostrobin
```{r Pyraclostrobin}
## Pyraclostrobin
pyraclostrobin.plug.discs <-  plug.discs %>% filter(Fungicide== "pyraclostrobin") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
pyraclostrobin.plug.discs.filtered <-  pyraclostrobin.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
pyraclostrobin.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 

# transforming to log 
pyraclostrobin.plug.discs.filtered.2 <-  pyraclostrobin.plug.discs.filtered %>% 
  mutate(log.inhibition= log(inhibition))
###
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
pyraclostrobin.plug.discs.filtered.2 %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$log.inhibition)))


# no parametric test between experimental repeatlicates and experiment, there is differenc between experiment and experimental replicates, so I cant join data from experimental replicates

pyraclostrobin.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experimental_replicate, 
    data = .) 


pyraclostrobin.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experiment, 
    data = .) 

# Now Dunn test

 pyraclostrobin.plug.discs.filtered  %>% DunnTest(inhibition ~ experiment,data = ., method = "bonferroni")
#P VALUE 0.000000000000079 *** plug-paper




```
## Thiophanate_methyl
```{r Thiophanate_methyl}

TM.plug.discs <-  plug.discs %>% filter(Fungicide== "thiophanate_methyl") %>% 
rename(response=fungicide) %>% 
  select(-Fungicide)
   
TM.plug.discs.filtered <-  TM.plug.discs%>%
  group_by(ID, experiment) %>%
  mutate(response_range = list(get_range(response))) %>%
  unnest() %>%
  mutate(control_range = list(get_range(control))) %>%
  unnest() %>%
  filter(response <= upper &
           response >= lower,
         control <= upper1 & control >= lower1) %>%
  ungroup() %>%
  select(c(ID, experiment,  experimental_replicate, rep, response, control)) %>% 

# Percent inhibition is (control - funcide) / (control)
  mutate(inhibition = 100*((control - response)/control)) %>%
  #taking again outliers based on inhibition
group_by(ID, experiment) %>%
  mutate(inhibition_range = list(get_range(inhibition))) %>%
  unnest() %>%
  filter(inhibition <= upper &
           inhibition >= lower) %>%
  ungroup()
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
TM.plug.discs.filtered %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$inhibition))) 

# transforming to square
TM.plug.discs.filtered.2 <-  TM.plug.discs.filtered %>% 
  mutate(square.inhibition= inhibition^2)
###
## shapiro test for normality between groups of experimental replicates. There are no normality between experimental replicates
TM.plug.discs.filtered.2 %>% 
group_by(experimental_replicate) %>%
  do(tidy(shapiro.test(.$square.inhibition)))


# non parametric test between experimental repeatlicates and experiment, there is differenc between experiment and no between experimental replicates, so I can join data from experimental replicates

TM.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experimental_replicate, 
    data = .) 


TM.plug.discs.filtered  %>% 
 kruskal.test(inhibition ~ experiment, 
    data = .) 

# Now Dunn test

 TM.plug.discs.filtered  %>% DunnTest(inhibition ~ experiment,data = ., method = "bonferroni")
#P VALUE 0.0456 * plug-paper


```

